<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
    <link rel="stylesheet" type="text/css" href="/Stylesheets/jqcloud.css">
    <link rel="stylesheet" href="/vendor/progressbar/dataurl.css">
    <script src="/vendor/progressbar/pace.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    {% block head %}
    {% endblock %}
    <style>
    a {
        text-decoration: none;
        color: #000000;
    }
    .ui-autocomplete {
      max-height: 100px;
      overflow-y: scroll;
      overflow-x: hidden;
    }
   * html .ui-autocomplete {
      height: 100px;
    }
    #city { width: 25em; }
    </style>
    <script>
    $(function() {
    function log( message ) {
      $( "<div>" ).text( message ).prependTo( "#log" );
      $( "#log" ).scrollTop( 0 );
    }
 
    $( "#tags" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/auto",
          dataType: "jsonp",
          data: {
            q: request.term
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 3,
      select: function( event, ui ) {
        log( ui.item ?
          "Selected: " + ui.item.label :
          "Nothing selected, input was " + this.value);
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
    });
  });
   </script>  
</head>

<body bgcolor= white>

    <div id="wordCloudHeader">
        <h1><a href="http://localhost:3000/">{{ title }}</a><h1>
    </div>

    <div id="wordCloud"></div>

    <div id="paperSearch">
      <div align:"center" class="ui-widget">
          <form method='get' action='/cloud/new'>
              <div id="radioButtons">
                Search by:
                <input type='radio' name='type' value="keyword" checked>Keyword
                <input type='radio' name='type' value="author"> Author
              </div>
              <div id="dropDownMenu">
                Number of Papers:
                <select name="limit">
                  <option value="10">10</option>
                  <option value="20">20</option>
                  <option value="30">30</option>
                  <option value="40">40</option>
                  <option value="50">50</option>
                  <option value="60">60</option>
                  <option value="70">70</option>
                  <option value="80">80</option>
                  <option value="90">90</option>
                  <option value="100">100</option>
                </select>
              </div>
              <input type=text id="tags" name="search" placeholder="Search away..." required>
              <input type="submit" class="buttons" value="Submit">
              {% block search %}{% endblock %}
          </form>
          {% block addartist %}{% endblock %}
      </div>
    </div>
<script type="text/javascript">
      var searchTerm = document.querySelector('input[type="text"]');
    searchTerm.oninvalid = function(e) {
    e.target.setCustomValidity("");
    if (!e.target.validity.valid) { e.target.setCustomValidity("Please enter a valid keyword or author"); }
    };
</script>
</body>
</html>
