<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
    <link rel="stylesheet" type="text/css" href="/Stylesheets/jqcloud.css">
    <link rel="stylesheet" href="/vendor/progressbar/dataurl.css">
    <script src="/vendor/progressbar/pace.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript" src="vendor/html2canvas.js"></script>
    <script src = "./wordCloud.js"> </script>
    {% block head %}
    {% endblock %}
    <style>
    a 
        text-decoration: none;
        color: #000000;
    }
    .ui-autocomplete {
      max-height: 100px;
      overflow-y: scroll;
      overflow-x: hidden;
    }
   * html .ui-autocomplete {
      height: 100px;
    }
    #city { width: 25em; }
    </style>
</head>

<body bgcolor= white>

    <div id="wordCloudHeader">
        <h1><a href="http://localhost:3000/">{{ title }}</a><h1>
    </div>

    <div id="wordCloud"></div>

    <div id="paperSearch">
      <div align:"center" class="ui-widget">
          <form method='get' action='/cloud'>
              <div id="radioButtons">
                Search by:
                <input type='radio' name='type' value="keyword" checked>Keyword
                <input type='radio' name='type' value="author"> Author
              </div>
              <div id="paperLimit">
                Number of Papers:
                <input type='number' min = "0" step = "1" value = "10" id="limit" name="limit" style = "max-width: 80px;">
              </div>
              <input type=text id="tags" name="search" placeholder="Search away..." required>
              <input type="submit" class="buttons" value="Submit">
							<div id="historyMenu">
                <select name="history" onChange="window.location.href=this.value">
                  {% for term,id in history %}
                    <option value="history?cloudid={{ id }}">{{ term }}</option> // need to default selected to last
                  {% endfor %}
                </select>
              </div>
              <button type="button" class="buttons" id="printWordCloud">Print Word Cloud</button
              {% block search %}{% endblock %}
          </form>
          {% block addartist %}{% endblock %}
      </div>
    </div>
<script type="text/javascript">
      var searchTerm = document.querySelector('input[type="text"]')
    searchTerm.oninvalid = function(e) {  
    e.target.setCustomValidity("");
    if (!e.target.validity.valid) { e.target.setCustomValidity("Please enter a valid keyword or author"); }
    };
</script>
</body>
</html>
