<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
    <script src = "./main.js"> </script>
     <style>
        a {
            text-decoration: none;
            color: #000000;
        }
        table, th, td {
            padding: 5px;
            text-align: left;
        }
    </style>
</head>
<body bgcolor="#A4A4A4">
    <div class="wrapper">
        <div id="paperHeader">
            <h1><a href="http://localhost:3000/">{{ title }}</a></h1>
            <h2>"{{ searchword }}"</h2> 
        </div>

        <div class="footer">
            <div>
                <form method='get' action='previous.html'>
                    <input type="submit" class="buttons" value="Back" onClick="history.back();return false;" style="width: 8%">
                </form>
                <form id = "export" method='get'>
                    <input type="button" onclick= "exportFunc()" value="Export to PDF">
                </form>
                <form id = "subset" method='get'>
                    <input type="button" onclick = "ssCloud()" value="Subset Feature">
                </form>
            </div>
        </div>
        <div id = "paperTitles">
                <table id="t01" rules="rows" max-width=100%>
                    <col style="width:1%">
                    <col style="width:15%">
                    <col style="width:10%">
                    <col style="width:15%">
                    <col style="width:1%">
                    <col style="width:1%">
                    <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Journal</th>
                    <th>Link</th>
                    <th>Frequency</th>      
                    </tr>
                    {% for paper in papers %}
                        <tr>
                        <td><input type="checkbox" name="papers"></td>
                        <td>
                        {% for word in paper.title %}
                        <a href="/cloud/?type=keyword&limit=10&search={{word}}">{{ word }} </a>
                        {% endfor %}
                        </td>
                        <td>
                        {% for author in paper.author %}
                        <a href="/cloud/?type=author&limit=10&search={{author}}">{{ author }} </a>
                        {% endfor %} 
                        </td>
                        <td>
                        <a href="/papers?term='{{ paper.journal }}'"> {{ paper.journal }}  </a>
                        </td>
                        <td>
                        <a href= {{ paper.link }} target="_blank"> X </a>
                        </td>
                        <td> {{ paper.frequency }} </td>
                        </tr>
                    {% endfor %}
                </table>
        </div>
       <div class="push"></div>
    </div>
</body>
</html>
