{% extends "home.phtml" %}

{% block head %} 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script type="text/javascript" src="/jqcloud-1.0.4.js"></script>
<script type="text/javascript">
var word_array = {{ wordArray | raw }};

  $(function() {
    // When DOM is ready, select the container element and call the jQCloud method, passing the array of words as the first argument.
    $("#wordCloud").jQCloud(word_array);
  });
</script>
{% endblock %}

{% block search %}
{{ parent() }}
{% endblock %}

{% block addartist %}
{% endblock %}
